name: Build Android
run-name: Creating Production Ready Android App 🚀
on:
  schedule:
    - cron: '0 4 * * 0'
  workflow_dispatch:

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
        with:
          ref: master

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'

      - name: check version
        run: |
          pip install -r requirements.txt
          python version_check.py

      - name: Install HUB
        run: sudo apt-get update && sudo apt-get install -y hub zipalign git

      - name: git update
        shell: bash
        run: |
          git config --global user.email fgfgui_link@outlook.com
          git config --global user.name link-fgfgui
          git add -u
          git commit -m '1'
          hub push origin
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          
      - name: download gh pages
        run: |
          wget https://github.com/MetaCubeX/metacubexd/archive/refs/heads/gh-pages.zip
          unzip gh-pages.zip

      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "17"

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 19.x

      - name: install dependencies
        run: npm ci	

      - name: Add android folder if not present
        run: if [ ! -d "./android" ]; then npx cap add android; fi

      - name: Capacitor update
        run: npx cap update

      - name: Capacitor copy
        run: npx cap copy
      
      # TODO: Check for folder structure in README for generating splash screen 
      - name: Generate icons and splash screen to android folder 
        run:  if [ -d "./resources" ]; then npm install @capacitor/assets --save-dev && npx capacitor-assets generate --android; fi

      - name: AndroidManifestModify
        run: rm android/app/src/main/AndroidManifest.xml && cp AndroidManifest.xml android/app/src/main/AndroidManifest.xml

      - name: Build app
        run: cd android && ./gradlew assembleRelease

      - name: Extract Android signing key from env
        run: |
          echo "${{ secrets.RELEASE_KEYSTORE }}" > android/release.jks.base64
          base64 -d android/release.jks.base64 > android/release.decrypted.jks

      - name: Sign dev build
        run: jarsigner -keystore android/release.decrypted.jks -storepass "${{ secrets.RELEASE_KEYSTORE_PASSWORD }}" ./android/app/build/outputs/apk/release/app-release-unsigned.apk release && zipalign 4 ./android/app/build/outputs/apk/release/app-release-unsigned.apk ./app-release-signed.apk && cp ./app-release-signed.apk ./android/app/build/outputs/apk/release/app-release-signed.apk

      - name: Set Tag
        id: current-datetime
        run: echo "CURRENT_DATETIME=$(date +'%Y-%m-%d-%H_%M_%S%z')" >> "$GITHUB_OUTPUT"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: ./android/app/build/outputs/

      - name: Build Release
        shell: bash
        run: |
          hub release create $(cat version) \
          -m "v$(cat version) UPDATE!" \
          -a app-release-signed.apk
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
